/**
 * libcurl constants
 * Based on curl.h - https://curl.se/libcurl/c/
 */

// Option type bases
const CURLOPTTYPE_LONG = 0;
const CURLOPTTYPE_OBJECTPOINT = 10000;
const CURLOPTTYPE_FUNCTIONPOINT = 20000;
const CURLOPTTYPE_OFF_T = 30000;
const CURLOPTTYPE_BLOB = 40000;
const CURLOPTTYPE_STRINGPOINT = CURLOPTTYPE_OBJECTPOINT;
const CURLOPTTYPE_SLISTPOINT = CURLOPTTYPE_OBJECTPOINT;
const CURLOPTTYPE_CBPOINT = CURLOPTTYPE_OBJECTPOINT;

// Info type bases
const CURLINFO_STRING = 0x100000;
const CURLINFO_LONG = 0x200000;
const CURLINFO_DOUBLE = 0x300000;
const CURLINFO_SLIST = 0x400000;
const CURLINFO_PTR = 0x400000;
const CURLINFO_SOCKET = 0x500000;
const CURLINFO_OFF_T = 0x600000;

/**
 * CURLcode - Error codes returned by libcurl functions
 */
export const CurlCode = {
  CURLE_OK: 0,
  CURLE_UNSUPPORTED_PROTOCOL: 1,
  CURLE_FAILED_INIT: 2,
  CURLE_URL_MALFORMAT: 3,
  CURLE_NOT_BUILT_IN: 4,
  CURLE_COULDNT_RESOLVE_PROXY: 5,
  CURLE_COULDNT_RESOLVE_HOST: 6,
  CURLE_COULDNT_CONNECT: 7,
  CURLE_WEIRD_SERVER_REPLY: 8,
  CURLE_REMOTE_ACCESS_DENIED: 9,
  CURLE_FTP_ACCEPT_FAILED: 10,
  CURLE_FTP_WEIRD_PASS_REPLY: 11,
  CURLE_FTP_ACCEPT_TIMEOUT: 12,
  CURLE_FTP_WEIRD_PASV_REPLY: 13,
  CURLE_FTP_WEIRD_227_FORMAT: 14,
  CURLE_FTP_CANT_GET_HOST: 15,
  CURLE_HTTP2: 16,
  CURLE_FTP_COULDNT_SET_TYPE: 17,
  CURLE_PARTIAL_FILE: 18,
  CURLE_FTP_COULDNT_RETR_FILE: 19,
  CURLE_OBSOLETE20: 20,
  CURLE_QUOTE_ERROR: 21,
  CURLE_HTTP_RETURNED_ERROR: 22,
  CURLE_WRITE_ERROR: 23,
  CURLE_OBSOLETE24: 24,
  CURLE_UPLOAD_FAILED: 25,
  CURLE_READ_ERROR: 26,
  CURLE_OUT_OF_MEMORY: 27,
  CURLE_OPERATION_TIMEDOUT: 28,
  CURLE_OBSOLETE29: 29,
  CURLE_FTP_PORT_FAILED: 30,
  CURLE_FTP_COULDNT_USE_REST: 31,
  CURLE_OBSOLETE32: 32,
  CURLE_RANGE_ERROR: 33,
  CURLE_HTTP_POST_ERROR: 34,
  CURLE_SSL_CONNECT_ERROR: 35,
  CURLE_BAD_DOWNLOAD_RESUME: 36,
  CURLE_FILE_COULDNT_READ_FILE: 37,
  CURLE_LDAP_CANNOT_BIND: 38,
  CURLE_LDAP_SEARCH_FAILED: 39,
  CURLE_OBSOLETE40: 40,
  CURLE_FUNCTION_NOT_FOUND: 41,
  CURLE_ABORTED_BY_CALLBACK: 42,
  CURLE_BAD_FUNCTION_ARGUMENT: 43,
  CURLE_OBSOLETE44: 44,
  CURLE_INTERFACE_FAILED: 45,
  CURLE_OBSOLETE46: 46,
  CURLE_TOO_MANY_REDIRECTS: 47,
  CURLE_UNKNOWN_OPTION: 48,
  CURLE_SETOPT_OPTION_SYNTAX: 49,
  CURLE_OBSOLETE50: 50,
  CURLE_OBSOLETE51: 51,
  CURLE_GOT_NOTHING: 52,
  CURLE_SSL_ENGINE_NOTFOUND: 53,
  CURLE_SSL_ENGINE_SETFAILED: 54,
  CURLE_SEND_ERROR: 55,
  CURLE_RECV_ERROR: 56,
  CURLE_OBSOLETE57: 57,
  CURLE_SSL_CERTPROBLEM: 58,
  CURLE_SSL_CIPHER: 59,
  CURLE_PEER_FAILED_VERIFICATION: 60,
  CURLE_BAD_CONTENT_ENCODING: 61,
  CURLE_OBSOLETE62: 62,
  CURLE_FILESIZE_EXCEEDED: 63,
  CURLE_USE_SSL_FAILED: 64,
  CURLE_SEND_FAIL_REWIND: 65,
  CURLE_SSL_ENGINE_INITFAILED: 66,
  CURLE_LOGIN_DENIED: 67,
  CURLE_TFTP_NOTFOUND: 68,
  CURLE_TFTP_PERM: 69,
  CURLE_REMOTE_DISK_FULL: 70,
  CURLE_TFTP_ILLEGAL: 71,
  CURLE_TFTP_UNKNOWNID: 72,
  CURLE_REMOTE_FILE_EXISTS: 73,
  CURLE_TFTP_NOSUCHUSER: 74,
  CURLE_OBSOLETE75: 75,
  CURLE_OBSOLETE76: 76,
  CURLE_SSL_CACERT_BADFILE: 77,
  CURLE_REMOTE_FILE_NOT_FOUND: 78,
  CURLE_SSH: 79,
  CURLE_SSL_SHUTDOWN_FAILED: 80,
  CURLE_AGAIN: 81,
  CURLE_SSL_CRL_BADFILE: 82,
  CURLE_SSL_ISSUER_ERROR: 83,
  CURLE_FTP_PRET_FAILED: 84,
  CURLE_RTSP_CSEQ_ERROR: 85,
  CURLE_RTSP_SESSION_ERROR: 86,
  CURLE_FTP_BAD_FILE_LIST: 87,
  CURLE_CHUNK_FAILED: 88,
  CURLE_NO_CONNECTION_AVAILABLE: 89,
  CURLE_SSL_PINNEDPUBKEYNOTMATCH: 90,
  CURLE_SSL_INVALIDCERTSTATUS: 91,
  CURLE_HTTP2_STREAM: 92,
  CURLE_RECURSIVE_API_CALL: 93,
  CURLE_AUTH_ERROR: 94,
  CURLE_HTTP3: 95,
  CURLE_QUIC_CONNECT_ERROR: 96,
  CURLE_PROXY: 97,
  CURLE_SSL_CLIENTCERT: 98,
  CURLE_UNRECOVERABLE_POLL: 99,
  CURLE_TOO_LARGE: 100,
  CURLE_ECH_REQUIRED: 101,
} as const;

export type CurlCode = (typeof CurlCode)[keyof typeof CurlCode];

/**
 * CURLoption - Options for curl_easy_setopt
 */
export const CurlOpt = {
  // Behavior options
  CURLOPT_VERBOSE: CURLOPTTYPE_LONG + 41,
  CURLOPT_HEADER: CURLOPTTYPE_LONG + 42,
  CURLOPT_NOPROGRESS: CURLOPTTYPE_LONG + 43,
  CURLOPT_NOSIGNAL: CURLOPTTYPE_LONG + 99,
  CURLOPT_WILDCARDMATCH: CURLOPTTYPE_LONG + 197,

  // Callback options
  CURLOPT_WRITEFUNCTION: CURLOPTTYPE_FUNCTIONPOINT + 11,
  CURLOPT_WRITEDATA: CURLOPTTYPE_CBPOINT + 1,
  CURLOPT_READFUNCTION: CURLOPTTYPE_FUNCTIONPOINT + 12,
  CURLOPT_READDATA: CURLOPTTYPE_CBPOINT + 9,
  CURLOPT_HEADERFUNCTION: CURLOPTTYPE_FUNCTIONPOINT + 79,
  CURLOPT_HEADERDATA: CURLOPTTYPE_CBPOINT + 29,
  CURLOPT_PROGRESSFUNCTION: CURLOPTTYPE_FUNCTIONPOINT + 56,
  CURLOPT_PROGRESSDATA: CURLOPTTYPE_CBPOINT + 57,
  CURLOPT_XFERINFOFUNCTION: CURLOPTTYPE_FUNCTIONPOINT + 219,
  CURLOPT_XFERINFODATA: CURLOPTTYPE_CBPOINT + 57,
  CURLOPT_DEBUGFUNCTION: CURLOPTTYPE_FUNCTIONPOINT + 94,
  CURLOPT_DEBUGDATA: CURLOPTTYPE_CBPOINT + 95,
  CURLOPT_SOCKOPTFUNCTION: CURLOPTTYPE_FUNCTIONPOINT + 148,
  CURLOPT_SOCKOPTDATA: CURLOPTTYPE_CBPOINT + 149,
  CURLOPT_OPENSOCKETFUNCTION: CURLOPTTYPE_FUNCTIONPOINT + 163,
  CURLOPT_OPENSOCKETDATA: CURLOPTTYPE_CBPOINT + 164,
  CURLOPT_CLOSESOCKETFUNCTION: CURLOPTTYPE_FUNCTIONPOINT + 208,
  CURLOPT_CLOSESOCKETDATA: CURLOPTTYPE_CBPOINT + 209,
  CURLOPT_SEEKFUNCTION: CURLOPTTYPE_FUNCTIONPOINT + 167,
  CURLOPT_SEEKDATA: CURLOPTTYPE_CBPOINT + 168,
  CURLOPT_SSL_CTX_FUNCTION: CURLOPTTYPE_FUNCTIONPOINT + 108,
  CURLOPT_SSL_CTX_DATA: CURLOPTTYPE_CBPOINT + 109,

  // Error options
  CURLOPT_ERRORBUFFER: CURLOPTTYPE_OBJECTPOINT + 10,
  CURLOPT_STDERR: CURLOPTTYPE_OBJECTPOINT + 37,
  CURLOPT_FAILONERROR: CURLOPTTYPE_LONG + 45,

  // Network options
  CURLOPT_URL: CURLOPTTYPE_STRINGPOINT + 2,
  CURLOPT_PATH_AS_IS: CURLOPTTYPE_LONG + 234,
  CURLOPT_PROTOCOLS_STR: CURLOPTTYPE_STRINGPOINT + 318,
  CURLOPT_REDIR_PROTOCOLS_STR: CURLOPTTYPE_STRINGPOINT + 319,
  CURLOPT_DEFAULT_PROTOCOL: CURLOPTTYPE_STRINGPOINT + 238,
  CURLOPT_PROXY: CURLOPTTYPE_STRINGPOINT + 4,
  CURLOPT_PRE_PROXY: CURLOPTTYPE_STRINGPOINT + 262,
  CURLOPT_PROXYPORT: CURLOPTTYPE_LONG + 59,
  CURLOPT_PROXYTYPE: CURLOPTTYPE_LONG + 101,
  CURLOPT_NOPROXY: CURLOPTTYPE_STRINGPOINT + 177,
  CURLOPT_HTTPPROXYTUNNEL: CURLOPTTYPE_LONG + 61,
  CURLOPT_CONNECT_ONLY: CURLOPTTYPE_LONG + 141,
  CURLOPT_SOCKS5_AUTH: CURLOPTTYPE_LONG + 267,
  CURLOPT_SOCKS5_GSSAPI_SERVICE: CURLOPTTYPE_STRINGPOINT + 179,
  CURLOPT_SOCKS5_GSSAPI_NEC: CURLOPTTYPE_LONG + 180,
  CURLOPT_PROXY_SERVICE_NAME: CURLOPTTYPE_STRINGPOINT + 235,
  CURLOPT_HAPROXYPROTOCOL: CURLOPTTYPE_LONG + 274,
  CURLOPT_SERVICE_NAME: CURLOPTTYPE_STRINGPOINT + 236,
  CURLOPT_INTERFACE: CURLOPTTYPE_STRINGPOINT + 62,
  CURLOPT_LOCALPORT: CURLOPTTYPE_LONG + 139,
  CURLOPT_LOCALPORTRANGE: CURLOPTTYPE_LONG + 140,
  CURLOPT_DNS_CACHE_TIMEOUT: CURLOPTTYPE_LONG + 92,
  CURLOPT_DNS_USE_GLOBAL_CACHE: CURLOPTTYPE_LONG + 91,
  CURLOPT_DOH_URL: CURLOPTTYPE_STRINGPOINT + 279,
  CURLOPT_BUFFERSIZE: CURLOPTTYPE_LONG + 98,
  CURLOPT_PORT: CURLOPTTYPE_LONG + 3,
  CURLOPT_TCP_FASTOPEN: CURLOPTTYPE_LONG + 244,
  CURLOPT_TCP_NODELAY: CURLOPTTYPE_LONG + 121,
  CURLOPT_TCP_KEEPALIVE: CURLOPTTYPE_LONG + 213,
  CURLOPT_TCP_KEEPIDLE: CURLOPTTYPE_LONG + 214,
  CURLOPT_TCP_KEEPINTVL: CURLOPTTYPE_LONG + 215,
  CURLOPT_ADDRESS_SCOPE: CURLOPTTYPE_LONG + 171,
  CURLOPT_UNIX_SOCKET_PATH: CURLOPTTYPE_STRINGPOINT + 231,
  CURLOPT_ABSTRACT_UNIX_SOCKET: CURLOPTTYPE_STRINGPOINT + 264,

  // Auth options
  CURLOPT_NETRC: CURLOPTTYPE_LONG + 51,
  CURLOPT_NETRC_FILE: CURLOPTTYPE_STRINGPOINT + 118,
  CURLOPT_USERPWD: CURLOPTTYPE_STRINGPOINT + 5,
  CURLOPT_PROXYUSERPWD: CURLOPTTYPE_STRINGPOINT + 6,
  CURLOPT_USERNAME: CURLOPTTYPE_STRINGPOINT + 173,
  CURLOPT_PASSWORD: CURLOPTTYPE_STRINGPOINT + 174,
  CURLOPT_LOGIN_OPTIONS: CURLOPTTYPE_STRINGPOINT + 224,
  CURLOPT_PROXYUSERNAME: CURLOPTTYPE_STRINGPOINT + 175,
  CURLOPT_PROXYPASSWORD: CURLOPTTYPE_STRINGPOINT + 176,
  CURLOPT_HTTPAUTH: CURLOPTTYPE_LONG + 107,
  CURLOPT_TLSAUTH_USERNAME: CURLOPTTYPE_STRINGPOINT + 204,
  CURLOPT_TLSAUTH_PASSWORD: CURLOPTTYPE_STRINGPOINT + 205,
  CURLOPT_TLSAUTH_TYPE: CURLOPTTYPE_STRINGPOINT + 206,
  CURLOPT_PROXYAUTH: CURLOPTTYPE_LONG + 111,
  CURLOPT_SASL_AUTHZID: CURLOPTTYPE_STRINGPOINT + 289,
  CURLOPT_SASL_IR: CURLOPTTYPE_LONG + 218,
  CURLOPT_XOAUTH2_BEARER: CURLOPTTYPE_STRINGPOINT + 220,
  CURLOPT_DISALLOW_USERNAME_IN_URL: CURLOPTTYPE_LONG + 278,

  // HTTP options
  CURLOPT_AUTOREFERER: CURLOPTTYPE_LONG + 58,
  CURLOPT_ACCEPT_ENCODING: CURLOPTTYPE_STRINGPOINT + 102,
  CURLOPT_TRANSFER_ENCODING: CURLOPTTYPE_LONG + 207,
  CURLOPT_FOLLOWLOCATION: CURLOPTTYPE_LONG + 52,
  CURLOPT_UNRESTRICTED_AUTH: CURLOPTTYPE_LONG + 105,
  CURLOPT_MAXREDIRS: CURLOPTTYPE_LONG + 68,
  CURLOPT_POSTREDIR: CURLOPTTYPE_LONG + 161,
  CURLOPT_PUT: CURLOPTTYPE_LONG + 54,
  CURLOPT_POST: CURLOPTTYPE_LONG + 47,
  CURLOPT_POSTFIELDS: CURLOPTTYPE_OBJECTPOINT + 15,
  CURLOPT_POSTFIELDSIZE: CURLOPTTYPE_LONG + 60,
  CURLOPT_POSTFIELDSIZE_LARGE: CURLOPTTYPE_OFF_T + 120,
  CURLOPT_COPYPOSTFIELDS: CURLOPTTYPE_OBJECTPOINT + 165,
  CURLOPT_HTTPPOST: CURLOPTTYPE_OBJECTPOINT + 24,
  CURLOPT_REFERER: CURLOPTTYPE_STRINGPOINT + 16,
  CURLOPT_USERAGENT: CURLOPTTYPE_STRINGPOINT + 18,
  CURLOPT_HTTPHEADER: CURLOPTTYPE_SLISTPOINT + 23,
  CURLOPT_HEADEROPT: CURLOPTTYPE_LONG + 229,
  CURLOPT_PROXYHEADER: CURLOPTTYPE_SLISTPOINT + 228,
  CURLOPT_HTTP200ALIASES: CURLOPTTYPE_SLISTPOINT + 104,
  CURLOPT_COOKIE: CURLOPTTYPE_STRINGPOINT + 22,
  CURLOPT_COOKIEFILE: CURLOPTTYPE_STRINGPOINT + 31,
  CURLOPT_COOKIEJAR: CURLOPTTYPE_STRINGPOINT + 82,
  CURLOPT_COOKIESESSION: CURLOPTTYPE_LONG + 96,
  CURLOPT_COOKIELIST: CURLOPTTYPE_STRINGPOINT + 135,
  CURLOPT_ALTSVC: CURLOPTTYPE_STRINGPOINT + 287,
  CURLOPT_ALTSVC_CTRL: CURLOPTTYPE_LONG + 286,
  CURLOPT_HSTS: CURLOPTTYPE_STRINGPOINT + 300,
  CURLOPT_HSTS_CTRL: CURLOPTTYPE_LONG + 299,
  CURLOPT_HSTSREADFUNCTION: CURLOPTTYPE_FUNCTIONPOINT + 301,
  CURLOPT_HSTSREADDATA: CURLOPTTYPE_CBPOINT + 302,
  CURLOPT_HSTSWRITEFUNCTION: CURLOPTTYPE_FUNCTIONPOINT + 303,
  CURLOPT_HSTSWRITEDATA: CURLOPTTYPE_CBPOINT + 304,
  CURLOPT_HTTPGET: CURLOPTTYPE_LONG + 80,
  CURLOPT_REQUEST_TARGET: CURLOPTTYPE_STRINGPOINT + 266,
  CURLOPT_HTTP_VERSION: CURLOPTTYPE_LONG + 84,
  CURLOPT_HTTP09_ALLOWED: CURLOPTTYPE_LONG + 285,
  CURLOPT_IGNORE_CONTENT_LENGTH: CURLOPTTYPE_LONG + 136,
  CURLOPT_HTTP_CONTENT_DECODING: CURLOPTTYPE_LONG + 158,
  CURLOPT_HTTP_TRANSFER_DECODING: CURLOPTTYPE_LONG + 157,
  CURLOPT_EXPECT_100_TIMEOUT_MS: CURLOPTTYPE_LONG + 227,
  CURLOPT_PIPEWAIT: CURLOPTTYPE_LONG + 237,
  CURLOPT_STREAM_DEPENDS: CURLOPTTYPE_OBJECTPOINT + 240,
  CURLOPT_STREAM_DEPENDS_E: CURLOPTTYPE_OBJECTPOINT + 241,
  CURLOPT_STREAM_WEIGHT: CURLOPTTYPE_LONG + 239,
  CURLOPT_CUSTOMREQUEST: CURLOPTTYPE_STRINGPOINT + 36,
  CURLOPT_NOBODY: CURLOPTTYPE_LONG + 44,
  CURLOPT_MIMEPOST: CURLOPTTYPE_OBJECTPOINT + 269,
  CURLOPT_MIME_OPTIONS: CURLOPTTYPE_LONG + 315,

  // SMTP options
  CURLOPT_MAIL_FROM: CURLOPTTYPE_STRINGPOINT + 186,
  CURLOPT_MAIL_RCPT: CURLOPTTYPE_SLISTPOINT + 187,
  CURLOPT_MAIL_AUTH: CURLOPTTYPE_STRINGPOINT + 217,
  CURLOPT_MAIL_RCPT_ALLOWFAILS: CURLOPTTYPE_LONG + 290,

  // TFTP options
  CURLOPT_TFTP_BLKSIZE: CURLOPTTYPE_LONG + 178,
  CURLOPT_TFTP_NO_OPTIONS: CURLOPTTYPE_LONG + 242,

  // FTP options
  CURLOPT_FTPPORT: CURLOPTTYPE_STRINGPOINT + 17,
  CURLOPT_QUOTE: CURLOPTTYPE_SLISTPOINT + 28,
  CURLOPT_POSTQUOTE: CURLOPTTYPE_SLISTPOINT + 39,
  CURLOPT_PREQUOTE: CURLOPTTYPE_SLISTPOINT + 93,
  CURLOPT_DIRLISTONLY: CURLOPTTYPE_LONG + 48,
  CURLOPT_APPEND: CURLOPTTYPE_LONG + 50,
  CURLOPT_FTP_USE_EPRT: CURLOPTTYPE_LONG + 106,
  CURLOPT_FTP_USE_EPSV: CURLOPTTYPE_LONG + 85,
  CURLOPT_FTP_USE_PRET: CURLOPTTYPE_LONG + 188,
  CURLOPT_FTP_CREATE_MISSING_DIRS: CURLOPTTYPE_LONG + 110,
  CURLOPT_SERVER_RESPONSE_TIMEOUT: CURLOPTTYPE_LONG + 112,
  CURLOPT_FTP_ALTERNATIVE_TO_USER: CURLOPTTYPE_STRINGPOINT + 147,
  CURLOPT_FTP_SKIP_PASV_IP: CURLOPTTYPE_LONG + 137,
  CURLOPT_FTPSSLAUTH: CURLOPTTYPE_LONG + 129,
  CURLOPT_FTP_SSL_CCC: CURLOPTTYPE_LONG + 154,
  CURLOPT_FTP_ACCOUNT: CURLOPTTYPE_STRINGPOINT + 134,
  CURLOPT_FTP_FILEMETHOD: CURLOPTTYPE_LONG + 138,

  // RTSP options
  CURLOPT_RTSP_REQUEST: CURLOPTTYPE_LONG + 189,
  CURLOPT_RTSP_SESSION_ID: CURLOPTTYPE_STRINGPOINT + 190,
  CURLOPT_RTSP_STREAM_URI: CURLOPTTYPE_STRINGPOINT + 191,
  CURLOPT_RTSP_TRANSPORT: CURLOPTTYPE_STRINGPOINT + 192,
  CURLOPT_RTSP_CLIENT_CSEQ: CURLOPTTYPE_LONG + 193,
  CURLOPT_RTSP_SERVER_CSEQ: CURLOPTTYPE_LONG + 194,

  // Protocol options
  CURLOPT_TRANSFERTEXT: CURLOPTTYPE_LONG + 53,
  CURLOPT_PROXY_TRANSFER_MODE: CURLOPTTYPE_LONG + 166,
  CURLOPT_CRLF: CURLOPTTYPE_LONG + 27,
  CURLOPT_RANGE: CURLOPTTYPE_STRINGPOINT + 7,
  CURLOPT_RESUME_FROM: CURLOPTTYPE_LONG + 21,
  CURLOPT_RESUME_FROM_LARGE: CURLOPTTYPE_OFF_T + 116,
  CURLOPT_CURLU: CURLOPTTYPE_OBJECTPOINT + 282,
  CURLOPT_FILETIME: CURLOPTTYPE_LONG + 69,
  CURLOPT_TIMECONDITION: CURLOPTTYPE_LONG + 33,
  CURLOPT_TIMEVALUE: CURLOPTTYPE_LONG + 34,
  CURLOPT_TIMEVALUE_LARGE: CURLOPTTYPE_OFF_T + 270,

  // Connection options
  CURLOPT_TIMEOUT: CURLOPTTYPE_LONG + 13,
  CURLOPT_TIMEOUT_MS: CURLOPTTYPE_LONG + 155,
  CURLOPT_LOW_SPEED_LIMIT: CURLOPTTYPE_LONG + 19,
  CURLOPT_LOW_SPEED_TIME: CURLOPTTYPE_LONG + 20,
  CURLOPT_MAX_SEND_SPEED_LARGE: CURLOPTTYPE_OFF_T + 145,
  CURLOPT_MAX_RECV_SPEED_LARGE: CURLOPTTYPE_OFF_T + 146,
  CURLOPT_MAXCONNECTS: CURLOPTTYPE_LONG + 71,
  CURLOPT_FRESH_CONNECT: CURLOPTTYPE_LONG + 74,
  CURLOPT_FORBID_REUSE: CURLOPTTYPE_LONG + 75,
  CURLOPT_MAXAGE_CONN: CURLOPTTYPE_LONG + 288,
  CURLOPT_MAXLIFETIME_CONN: CURLOPTTYPE_LONG + 314,
  CURLOPT_CONNECTTIMEOUT: CURLOPTTYPE_LONG + 78,
  CURLOPT_CONNECTTIMEOUT_MS: CURLOPTTYPE_LONG + 156,
  CURLOPT_IPRESOLVE: CURLOPTTYPE_LONG + 113,
  CURLOPT_CONNECT_TO: CURLOPTTYPE_SLISTPOINT + 243,
  CURLOPT_RESOLVE: CURLOPTTYPE_SLISTPOINT + 203,
  CURLOPT_DNS_INTERFACE: CURLOPTTYPE_STRINGPOINT + 221,
  CURLOPT_DNS_LOCAL_IP4: CURLOPTTYPE_STRINGPOINT + 222,
  CURLOPT_DNS_LOCAL_IP6: CURLOPTTYPE_STRINGPOINT + 223,
  CURLOPT_DNS_SERVERS: CURLOPTTYPE_STRINGPOINT + 211,
  CURLOPT_DNS_SHUFFLE_ADDRESSES: CURLOPTTYPE_LONG + 275,
  CURLOPT_ACCEPTTIMEOUT_MS: CURLOPTTYPE_LONG + 212,
  CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS: CURLOPTTYPE_LONG + 271,
  CURLOPT_UPKEEP_INTERVAL_MS: CURLOPTTYPE_LONG + 281,

  // SSL/TLS options
  CURLOPT_SSLCERT: CURLOPTTYPE_STRINGPOINT + 25,
  CURLOPT_SSLCERT_BLOB: CURLOPTTYPE_BLOB + 291,
  CURLOPT_PROXY_SSLCERT: CURLOPTTYPE_STRINGPOINT + 254,
  CURLOPT_PROXY_SSLCERT_BLOB: CURLOPTTYPE_BLOB + 293,
  CURLOPT_SSLCERTTYPE: CURLOPTTYPE_STRINGPOINT + 86,
  CURLOPT_PROXY_SSLCERTTYPE: CURLOPTTYPE_STRINGPOINT + 255,
  CURLOPT_SSLKEY: CURLOPTTYPE_STRINGPOINT + 87,
  CURLOPT_SSLKEY_BLOB: CURLOPTTYPE_BLOB + 292,
  CURLOPT_PROXY_SSLKEY: CURLOPTTYPE_STRINGPOINT + 256,
  CURLOPT_PROXY_SSLKEY_BLOB: CURLOPTTYPE_BLOB + 294,
  CURLOPT_SSLKEYTYPE: CURLOPTTYPE_STRINGPOINT + 88,
  CURLOPT_PROXY_SSLKEYTYPE: CURLOPTTYPE_STRINGPOINT + 257,
  CURLOPT_KEYPASSWD: CURLOPTTYPE_STRINGPOINT + 26,
  CURLOPT_PROXY_KEYPASSWD: CURLOPTTYPE_STRINGPOINT + 258,
  CURLOPT_SSL_EC_CURVES: CURLOPTTYPE_STRINGPOINT + 298,
  CURLOPT_SSL_ENGINE: CURLOPTTYPE_STRINGPOINT + 89,
  CURLOPT_SSL_ENGINE_DEFAULT: CURLOPTTYPE_LONG + 90,
  CURLOPT_SSLVERSION: CURLOPTTYPE_LONG + 32,
  CURLOPT_PROXY_SSLVERSION: CURLOPTTYPE_LONG + 250,
  CURLOPT_SSL_VERIFYHOST: CURLOPTTYPE_LONG + 81,
  CURLOPT_DOH_SSL_VERIFYHOST: CURLOPTTYPE_LONG + 307,
  CURLOPT_PROXY_SSL_VERIFYHOST: CURLOPTTYPE_LONG + 249,
  CURLOPT_SSL_VERIFYPEER: CURLOPTTYPE_LONG + 64,
  CURLOPT_DOH_SSL_VERIFYPEER: CURLOPTTYPE_LONG + 306,
  CURLOPT_PROXY_SSL_VERIFYPEER: CURLOPTTYPE_LONG + 248,
  CURLOPT_SSL_VERIFYSTATUS: CURLOPTTYPE_LONG + 232,
  CURLOPT_DOH_SSL_VERIFYSTATUS: CURLOPTTYPE_LONG + 308,
  CURLOPT_CAINFO: CURLOPTTYPE_STRINGPOINT + 65,
  CURLOPT_CAINFO_BLOB: CURLOPTTYPE_BLOB + 309,
  CURLOPT_PROXY_CAINFO: CURLOPTTYPE_STRINGPOINT + 246,
  CURLOPT_PROXY_CAINFO_BLOB: CURLOPTTYPE_BLOB + 310,
  CURLOPT_ISSUERCERT: CURLOPTTYPE_STRINGPOINT + 170,
  CURLOPT_ISSUERCERT_BLOB: CURLOPTTYPE_BLOB + 295,
  CURLOPT_PROXY_ISSUERCERT: CURLOPTTYPE_STRINGPOINT + 296,
  CURLOPT_PROXY_ISSUERCERT_BLOB: CURLOPTTYPE_BLOB + 297,
  CURLOPT_CAPATH: CURLOPTTYPE_STRINGPOINT + 97,
  CURLOPT_PROXY_CAPATH: CURLOPTTYPE_STRINGPOINT + 247,
  CURLOPT_CRLFILE: CURLOPTTYPE_STRINGPOINT + 169,
  CURLOPT_PROXY_CRLFILE: CURLOPTTYPE_STRINGPOINT + 260,
  CURLOPT_CA_CACHE_TIMEOUT: CURLOPTTYPE_LONG + 321,
  CURLOPT_CERTINFO: CURLOPTTYPE_LONG + 172,
  CURLOPT_PINNEDPUBLICKEY: CURLOPTTYPE_STRINGPOINT + 230,
  CURLOPT_PROXY_PINNEDPUBLICKEY: CURLOPTTYPE_STRINGPOINT + 263,
  CURLOPT_RANDOM_FILE: CURLOPTTYPE_STRINGPOINT + 76,
  CURLOPT_EGDSOCKET: CURLOPTTYPE_STRINGPOINT + 77,
  CURLOPT_SSL_CIPHER_LIST: CURLOPTTYPE_STRINGPOINT + 83,
  CURLOPT_PROXY_SSL_CIPHER_LIST: CURLOPTTYPE_STRINGPOINT + 259,
  CURLOPT_TLS13_CIPHERS: CURLOPTTYPE_STRINGPOINT + 276,
  CURLOPT_PROXY_TLS13_CIPHERS: CURLOPTTYPE_STRINGPOINT + 277,
  CURLOPT_SSL_SESSIONID_CACHE: CURLOPTTYPE_LONG + 150,
  CURLOPT_SSL_OPTIONS: CURLOPTTYPE_LONG + 216,
  CURLOPT_SSL_ENABLE_ALPN: CURLOPTTYPE_LONG + 226,
  CURLOPT_PROXY_SSL_OPTIONS: CURLOPTTYPE_LONG + 261,
  CURLOPT_KRBLEVEL: CURLOPTTYPE_STRINGPOINT + 63,
  CURLOPT_GSSAPI_DELEGATION: CURLOPTTYPE_LONG + 210,

  // SSH options
  CURLOPT_SSH_AUTH_TYPES: CURLOPTTYPE_LONG + 151,
  CURLOPT_SSH_COMPRESSION: CURLOPTTYPE_LONG + 268,
  CURLOPT_SSH_HOST_PUBLIC_KEY_MD5: CURLOPTTYPE_STRINGPOINT + 162,
  CURLOPT_SSH_HOST_PUBLIC_KEY_SHA256: CURLOPTTYPE_STRINGPOINT + 311,
  CURLOPT_SSH_PUBLIC_KEYFILE: CURLOPTTYPE_STRINGPOINT + 152,
  CURLOPT_SSH_PRIVATE_KEYFILE: CURLOPTTYPE_STRINGPOINT + 153,
  CURLOPT_SSH_KNOWNHOSTS: CURLOPTTYPE_STRINGPOINT + 183,
  CURLOPT_SSH_KEYFUNCTION: CURLOPTTYPE_FUNCTIONPOINT + 184,
  CURLOPT_SSH_KEYDATA: CURLOPTTYPE_CBPOINT + 185,
  CURLOPT_SSH_HOSTKEYFUNCTION: CURLOPTTYPE_FUNCTIONPOINT + 316,
  CURLOPT_SSH_HOSTKEYDATA: CURLOPTTYPE_CBPOINT + 317,

  // WebSocket options
  CURLOPT_WS_OPTIONS: CURLOPTTYPE_LONG + 320,

  // Other options
  CURLOPT_PRIVATE: CURLOPTTYPE_OBJECTPOINT + 103,
  CURLOPT_SHARE: CURLOPTTYPE_OBJECTPOINT + 100,
  CURLOPT_NEW_FILE_PERMS: CURLOPTTYPE_LONG + 159,
  CURLOPT_NEW_DIRECTORY_PERMS: CURLOPTTYPE_LONG + 160,
  CURLOPT_TELNETOPTIONS: CURLOPTTYPE_SLISTPOINT + 70,

  // Upload/download options
  CURLOPT_UPLOAD: CURLOPTTYPE_LONG + 46,
  CURLOPT_UPLOAD_BUFFERSIZE: CURLOPTTYPE_LONG + 280,
  CURLOPT_INFILESIZE: CURLOPTTYPE_LONG + 14,
  CURLOPT_INFILESIZE_LARGE: CURLOPTTYPE_OFF_T + 115,
  CURLOPT_MAXFILESIZE: CURLOPTTYPE_LONG + 114,
  CURLOPT_MAXFILESIZE_LARGE: CURLOPTTYPE_OFF_T + 117,

  // Speed limit options
  CURLOPT_MAX_SEND_SPEED_LARGE_ALIAS: CURLOPTTYPE_OFF_T + 145,
  CURLOPT_MAX_RECV_SPEED_LARGE_ALIAS: CURLOPTTYPE_OFF_T + 146,

  // AWS Sigv4
  CURLOPT_AWS_SIGV4: CURLOPTTYPE_STRINGPOINT + 305,

  // Quick exit
  CURLOPT_QUICK_EXIT: CURLOPTTYPE_LONG + 322,

  // ECH
  CURLOPT_ECH: CURLOPTTYPE_STRINGPOINT + 323,
} as const;

export type CurlOpt = (typeof CurlOpt)[keyof typeof CurlOpt];

/**
 * CURLINFO - Options for curl_easy_getinfo
 */
export const CurlInfo = {
  CURLINFO_EFFECTIVE_URL: CURLINFO_STRING + 1,
  CURLINFO_RESPONSE_CODE: CURLINFO_LONG + 2,
  CURLINFO_TOTAL_TIME: CURLINFO_DOUBLE + 3,
  CURLINFO_NAMELOOKUP_TIME: CURLINFO_DOUBLE + 4,
  CURLINFO_CONNECT_TIME: CURLINFO_DOUBLE + 5,
  CURLINFO_PRETRANSFER_TIME: CURLINFO_DOUBLE + 6,
  CURLINFO_SIZE_UPLOAD: CURLINFO_DOUBLE + 7,
  CURLINFO_SIZE_UPLOAD_T: CURLINFO_OFF_T + 7,
  CURLINFO_SIZE_DOWNLOAD: CURLINFO_DOUBLE + 8,
  CURLINFO_SIZE_DOWNLOAD_T: CURLINFO_OFF_T + 8,
  CURLINFO_SPEED_DOWNLOAD: CURLINFO_DOUBLE + 9,
  CURLINFO_SPEED_DOWNLOAD_T: CURLINFO_OFF_T + 9,
  CURLINFO_SPEED_UPLOAD: CURLINFO_DOUBLE + 10,
  CURLINFO_SPEED_UPLOAD_T: CURLINFO_OFF_T + 10,
  CURLINFO_HEADER_SIZE: CURLINFO_LONG + 11,
  CURLINFO_REQUEST_SIZE: CURLINFO_LONG + 12,
  CURLINFO_SSL_VERIFYRESULT: CURLINFO_LONG + 13,
  CURLINFO_FILETIME: CURLINFO_LONG + 14,
  CURLINFO_FILETIME_T: CURLINFO_OFF_T + 14,
  CURLINFO_CONTENT_LENGTH_DOWNLOAD: CURLINFO_DOUBLE + 15,
  CURLINFO_CONTENT_LENGTH_DOWNLOAD_T: CURLINFO_OFF_T + 15,
  CURLINFO_CONTENT_LENGTH_UPLOAD: CURLINFO_DOUBLE + 16,
  CURLINFO_CONTENT_LENGTH_UPLOAD_T: CURLINFO_OFF_T + 16,
  CURLINFO_STARTTRANSFER_TIME: CURLINFO_DOUBLE + 17,
  CURLINFO_CONTENT_TYPE: CURLINFO_STRING + 18,
  CURLINFO_REDIRECT_TIME: CURLINFO_DOUBLE + 19,
  CURLINFO_REDIRECT_COUNT: CURLINFO_LONG + 20,
  CURLINFO_PRIVATE: CURLINFO_STRING + 21,
  CURLINFO_HTTP_CONNECTCODE: CURLINFO_LONG + 22,
  CURLINFO_HTTPAUTH_AVAIL: CURLINFO_LONG + 23,
  CURLINFO_PROXYAUTH_AVAIL: CURLINFO_LONG + 24,
  CURLINFO_OS_ERRNO: CURLINFO_LONG + 25,
  CURLINFO_NUM_CONNECTS: CURLINFO_LONG + 26,
  CURLINFO_SSL_ENGINES: CURLINFO_SLIST + 27,
  CURLINFO_COOKIELIST: CURLINFO_SLIST + 28,
  CURLINFO_LASTSOCKET: CURLINFO_LONG + 29,
  CURLINFO_FTP_ENTRY_PATH: CURLINFO_STRING + 30,
  CURLINFO_REDIRECT_URL: CURLINFO_STRING + 31,
  CURLINFO_PRIMARY_IP: CURLINFO_STRING + 32,
  CURLINFO_APPCONNECT_TIME: CURLINFO_DOUBLE + 33,
  CURLINFO_CERTINFO: CURLINFO_PTR + 34,
  CURLINFO_CONDITION_UNMET: CURLINFO_LONG + 35,
  CURLINFO_RTSP_SESSION_ID: CURLINFO_STRING + 36,
  CURLINFO_RTSP_CLIENT_CSEQ: CURLINFO_LONG + 37,
  CURLINFO_RTSP_SERVER_CSEQ: CURLINFO_LONG + 38,
  CURLINFO_RTSP_CSEQ_RECV: CURLINFO_LONG + 39,
  CURLINFO_PRIMARY_PORT: CURLINFO_LONG + 40,
  CURLINFO_LOCAL_IP: CURLINFO_STRING + 41,
  CURLINFO_LOCAL_PORT: CURLINFO_LONG + 42,
  CURLINFO_TLS_SESSION: CURLINFO_PTR + 43,
  CURLINFO_ACTIVESOCKET: CURLINFO_SOCKET + 44,
  CURLINFO_TLS_SSL_PTR: CURLINFO_PTR + 45,
  CURLINFO_HTTP_VERSION: CURLINFO_LONG + 46,
  CURLINFO_PROXY_SSL_VERIFYRESULT: CURLINFO_LONG + 47,
  CURLINFO_PROTOCOL: CURLINFO_LONG + 48,
  CURLINFO_SCHEME: CURLINFO_STRING + 49,
  CURLINFO_TOTAL_TIME_T: CURLINFO_OFF_T + 50,
  CURLINFO_NAMELOOKUP_TIME_T: CURLINFO_OFF_T + 51,
  CURLINFO_CONNECT_TIME_T: CURLINFO_OFF_T + 52,
  CURLINFO_PRETRANSFER_TIME_T: CURLINFO_OFF_T + 53,
  CURLINFO_STARTTRANSFER_TIME_T: CURLINFO_OFF_T + 54,
  CURLINFO_REDIRECT_TIME_T: CURLINFO_OFF_T + 55,
  CURLINFO_APPCONNECT_TIME_T: CURLINFO_OFF_T + 56,
  CURLINFO_RETRY_AFTER: CURLINFO_OFF_T + 57,
  CURLINFO_EFFECTIVE_METHOD: CURLINFO_STRING + 58,
  CURLINFO_PROXY_ERROR: CURLINFO_LONG + 59,
  CURLINFO_REFERER: CURLINFO_STRING + 60,
  CURLINFO_CAINFO: CURLINFO_STRING + 61,
  CURLINFO_CAPATH: CURLINFO_STRING + 62,
  CURLINFO_XFER_ID: CURLINFO_OFF_T + 63,
  CURLINFO_CONN_ID: CURLINFO_OFF_T + 64,
  CURLINFO_QUEUE_TIME_T: CURLINFO_OFF_T + 65,
  CURLINFO_USED_PROXY: CURLINFO_LONG + 66,
  CURLINFO_POSTTRANSFER_TIME_T: CURLINFO_OFF_T + 67,
} as const;

export type CurlInfo = (typeof CurlInfo)[keyof typeof CurlInfo];

/**
 * CURLMcode - Error codes for curl_multi functions
 */
export const CurlMCode = {
  CURLM_CALL_MULTI_PERFORM: -1,
  CURLM_OK: 0,
  CURLM_BAD_HANDLE: 1,
  CURLM_BAD_EASY_HANDLE: 2,
  CURLM_OUT_OF_MEMORY: 3,
  CURLM_INTERNAL_ERROR: 4,
  CURLM_BAD_SOCKET: 5,
  CURLM_UNKNOWN_OPTION: 6,
  CURLM_ADDED_ALREADY: 7,
  CURLM_RECURSIVE_API_CALL: 8,
  CURLM_WAKEUP_FAILURE: 9,
  CURLM_BAD_FUNCTION_ARGUMENT: 10,
  CURLM_ABORTED_BY_CALLBACK: 11,
  CURLM_UNRECOVERABLE_POLL: 12,
} as const;

export type CurlMCode = (typeof CurlMCode)[keyof typeof CurlMCode];

/**
 * CURLMoption - Options for curl_multi_setopt
 */
export const CurlMOpt = {
  CURLMOPT_SOCKETFUNCTION: 20001,
  CURLMOPT_SOCKETDATA: 10002,
  CURLMOPT_PIPELINING: 3,
  CURLMOPT_TIMERFUNCTION: 20004,
  CURLMOPT_TIMERDATA: 10005,
  CURLMOPT_MAXCONNECTS: 6,
  CURLMOPT_MAX_HOST_CONNECTIONS: 7,
  CURLMOPT_MAX_PIPELINE_LENGTH: 8,
  CURLMOPT_CONTENT_LENGTH_PENALTY_SIZE: 30009,
  CURLMOPT_CHUNK_LENGTH_PENALTY_SIZE: 30010,
  CURLMOPT_PIPELINING_SITE_BL: 10011,
  CURLMOPT_PIPELINING_SERVER_BL: 10012,
  CURLMOPT_MAX_TOTAL_CONNECTIONS: 13,
  CURLMOPT_PUSHFUNCTION: 20014,
  CURLMOPT_PUSHDATA: 10015,
  CURLMOPT_MAX_CONCURRENT_STREAMS: 16,
} as const;

export type CurlMOpt = (typeof CurlMOpt)[keyof typeof CurlMOpt];

/**
 * CURLMSG - Messages from curl_multi_info_read
 */
export const CurlMsg = {
  CURLMSG_NONE: 0,
  CURLMSG_DONE: 1,
} as const;

export type CurlMsg = (typeof CurlMsg)[keyof typeof CurlMsg];

/**
 * HTTP versions
 */
export const CurlHttpVersion = {
  CURL_HTTP_VERSION_NONE: 0,
  CURL_HTTP_VERSION_1_0: 1,
  CURL_HTTP_VERSION_1_1: 2,
  CURL_HTTP_VERSION_2_0: 3,
  CURL_HTTP_VERSION_2TLS: 4,
  CURL_HTTP_VERSION_2_PRIOR_KNOWLEDGE: 5,
  CURL_HTTP_VERSION_3: 30,
  CURL_HTTP_VERSION_3ONLY: 31,
} as const;

export type CurlHttpVersion = (typeof CurlHttpVersion)[keyof typeof CurlHttpVersion];

/**
 * SSL versions
 */
export const CurlSslVersion = {
  CURL_SSLVERSION_DEFAULT: 0,
  CURL_SSLVERSION_TLSv1: 1,
  CURL_SSLVERSION_SSLv2: 2,
  CURL_SSLVERSION_SSLv3: 3,
  CURL_SSLVERSION_TLSv1_0: 4,
  CURL_SSLVERSION_TLSv1_1: 5,
  CURL_SSLVERSION_TLSv1_2: 6,
  CURL_SSLVERSION_TLSv1_3: 7,
  CURL_SSLVERSION_MAX_DEFAULT: 0x10000,
  CURL_SSLVERSION_MAX_TLSv1_0: 0x40000,
  CURL_SSLVERSION_MAX_TLSv1_1: 0x50000,
  CURL_SSLVERSION_MAX_TLSv1_2: 0x60000,
  CURL_SSLVERSION_MAX_TLSv1_3: 0x70000,
} as const;

export type CurlSslVersion = (typeof CurlSslVersion)[keyof typeof CurlSslVersion];

/**
 * Authentication types
 */
export const CurlAuth = {
  CURLAUTH_NONE: 0,
  CURLAUTH_BASIC: 1 << 0,
  CURLAUTH_DIGEST: 1 << 1,
  CURLAUTH_NEGOTIATE: 1 << 2,
  CURLAUTH_NTLM: 1 << 3,
  CURLAUTH_DIGEST_IE: 1 << 4,
  CURLAUTH_NTLM_WB: 1 << 5,
  CURLAUTH_BEARER: 1 << 6,
  CURLAUTH_AWS_SIGV4: 1 << 7,
  CURLAUTH_ONLY: 1 << 31,
  CURLAUTH_ANY: ~(1 << 4), // ~CURLAUTH_DIGEST_IE
  CURLAUTH_ANYSAFE: ~((1 << 0) | (1 << 4)), // ~(CURLAUTH_BASIC | CURLAUTH_DIGEST_IE)
} as const;

export type CurlAuth = (typeof CurlAuth)[keyof typeof CurlAuth];

/**
 * Proxy types
 */
export const CurlProxyType = {
  CURLPROXY_HTTP: 0,
  CURLPROXY_HTTP_1_0: 1,
  CURLPROXY_HTTPS: 2,
  CURLPROXY_HTTPS2: 3,
  CURLPROXY_SOCKS4: 4,
  CURLPROXY_SOCKS5: 5,
  CURLPROXY_SOCKS4A: 6,
  CURLPROXY_SOCKS5_HOSTNAME: 7,
} as const;

export type CurlProxyType = (typeof CurlProxyType)[keyof typeof CurlProxyType];

/**
 * Socket action for curl_multi_socket_action
 */
export const CurlPoll = {
  CURL_POLL_NONE: 0,
  CURL_POLL_IN: 1,
  CURL_POLL_OUT: 2,
  CURL_POLL_INOUT: 3,
  CURL_POLL_REMOVE: 4,
} as const;

export type CurlPoll = (typeof CurlPoll)[keyof typeof CurlPoll];

/**
 * Socket callback events
 */
export const CurlCSelect = {
  CURL_CSELECT_IN: 0x01,
  CURL_CSELECT_OUT: 0x02,
  CURL_CSELECT_ERR: 0x04,
} as const;

export type CurlCSelect = (typeof CurlCSelect)[keyof typeof CurlCSelect];

/**
 * Special socket value for timeout
 */
export const CURL_SOCKET_TIMEOUT = -1;

/**
 * WebSocket flags
 */
export const CurlWsFlag = {
  CURLWS_TEXT: 1 << 0,
  CURLWS_BINARY: 1 << 1,
  CURLWS_CONT: 1 << 2,
  CURLWS_CLOSE: 1 << 3,
  CURLWS_PING: 1 << 4,
  CURLWS_PONG: 1 << 5,
  CURLWS_OFFSET: 1 << 6,
} as const;

export type CurlWsFlag = (typeof CurlWsFlag)[keyof typeof CurlWsFlag];

/**
 * WebSocket options for CURLOPT_WS_OPTIONS
 */
export const CurlWsOpt = {
  CURLWS_RAW_MODE: 1 << 0,
} as const;

export type CurlWsOpt = (typeof CurlWsOpt)[keyof typeof CurlWsOpt];

/**
 * IP resolve options
 */
export const CurlIpResolve = {
  CURL_IPRESOLVE_WHATEVER: 0,
  CURL_IPRESOLVE_V4: 1,
  CURL_IPRESOLVE_V6: 2,
} as const;

export type CurlIpResolve = (typeof CurlIpResolve)[keyof typeof CurlIpResolve];

/**
 * Netrc options
 */
export const CurlNetrc = {
  CURL_NETRC_IGNORED: 0,
  CURL_NETRC_OPTIONAL: 1,
  CURL_NETRC_REQUIRED: 2,
} as const;

export type CurlNetrc = (typeof CurlNetrc)[keyof typeof CurlNetrc];

/**
 * FTP method options
 */
export const CurlFtpMethod = {
  CURLFTPMETHOD_DEFAULT: 0,
  CURLFTPMETHOD_MULTICWD: 1,
  CURLFTPMETHOD_NOCWD: 2,
  CURLFTPMETHOD_SINGLECWD: 3,
} as const;

export type CurlFtpMethod = (typeof CurlFtpMethod)[keyof typeof CurlFtpMethod];

/**
 * Time condition options
 */
export const CurlTimeCond = {
  CURL_TIMECOND_NONE: 0,
  CURL_TIMECOND_IFMODSINCE: 1,
  CURL_TIMECOND_IFUNMODSINCE: 2,
} as const;

export type CurlTimeCond = (typeof CurlTimeCond)[keyof typeof CurlTimeCond];

/**
 * Header options for CURLOPT_HEADEROPT
 */
export const CurlHeader = {
  CURLHEADER_UNIFIED: 0,
  CURLHEADER_SEPARATE: 1 << 0,
} as const;

export type CurlHeader = (typeof CurlHeader)[keyof typeof CurlHeader];

/**
 * Post redirect options
 */
export const CurlRedir = {
  CURL_REDIR_GET_ALL: 0,
  CURL_REDIR_POST_301: 1,
  CURL_REDIR_POST_302: 2,
  CURL_REDIR_POST_303: 4,
  CURL_REDIR_POST_ALL: 7,
} as const;

export type CurlRedir = (typeof CurlRedir)[keyof typeof CurlRedir];

/**
 * SSL options for CURLOPT_SSL_OPTIONS
 */
export const CurlSslOpt = {
  CURLSSLOPT_ALLOW_BEAST: 1 << 0,
  CURLSSLOPT_NO_REVOKE: 1 << 1,
  CURLSSLOPT_NO_PARTIALCHAIN: 1 << 2,
  CURLSSLOPT_REVOKE_BEST_EFFORT: 1 << 3,
  CURLSSLOPT_NATIVE_CA: 1 << 4,
  CURLSSLOPT_AUTO_CLIENT_CERT: 1 << 5,
} as const;

export type CurlSslOpt = (typeof CurlSslOpt)[keyof typeof CurlSslOpt];

/**
 * GSSAPI delegation options
 */
export const CurlGssApi = {
  CURLGSSAPI_DELEGATION_NONE: 0,
  CURLGSSAPI_DELEGATION_POLICY_FLAG: 1 << 0,
  CURLGSSAPI_DELEGATION_FLAG: 1 << 1,
} as const;

export type CurlGssApi = (typeof CurlGssApi)[keyof typeof CurlGssApi];

/**
 * Use SSL options
 */
export const CurlUseSsl = {
  CURLUSESSL_NONE: 0,
  CURLUSESSL_TRY: 1,
  CURLUSESSL_CONTROL: 2,
  CURLUSESSL_ALL: 3,
} as const;

export type CurlUseSsl = (typeof CurlUseSsl)[keyof typeof CurlUseSsl];

/**
 * MIME options
 */
export const CurlMimeOpt = {
  CURLMIMEOPT_FORMESCAPE: 1 << 0,
} as const;

export type CurlMimeOpt = (typeof CurlMimeOpt)[keyof typeof CurlMimeOpt];

/**
 * Pipelining options for CURLMOPT_PIPELINING
 */
export const CurlPipe = {
  CURLPIPE_NOTHING: 0,
  CURLPIPE_HTTP1: 1,
  CURLPIPE_MULTIPLEX: 2,
} as const;

export type CurlPipe = (typeof CurlPipe)[keyof typeof CurlPipe];

// ============================================================================
// curl-impersonate specific options (not in standard libcurl)
// These options only work with libcurl-impersonate builds
// ============================================================================

/**
 * curl-impersonate specific CURLOPT options for TLS/HTTP2 fingerprinting
 */
export const CurlImpersonateOpt = {
  // TLS fingerprinting options
  /** Base header for impersonation (string) */
  CURLOPT_HTTPBASEHEADER: CURLOPTTYPE_STRINGPOINT + 1000,
  /** Signature hash algorithms (string, comma-separated) */
  CURLOPT_SSL_SIG_HASH_ALGS: CURLOPTTYPE_STRINGPOINT + 1001,
  /** Enable ALPS extension (long, 0 or 1) */
  CURLOPT_SSL_ENABLE_ALPS: CURLOPTTYPE_LONG + 1002,
  /** Certificate compression algorithm (string: "zlib" or "brotli") */
  CURLOPT_SSL_CERT_COMPRESSION: CURLOPTTYPE_STRINGPOINT + 1003,
  /** Enable session ticket extension (long, 0 or 1) */
  CURLOPT_SSL_ENABLE_TICKET: CURLOPTTYPE_LONG + 1004,

  // HTTP/2 fingerprinting options
  /** HTTP/2 pseudo header order (string, e.g., "masp") */
  CURLOPT_HTTP2_PSEUDO_HEADERS_ORDER: CURLOPTTYPE_STRINGPOINT + 1005,
  /** HTTP/2 SETTINGS frame values (string, e.g., "1:65536;3:1000") */
  CURLOPT_HTTP2_SETTINGS: CURLOPTTYPE_STRINGPOINT + 1006,
  /** Permute TLS extensions randomly (long, 0 or 1) */
  CURLOPT_SSL_PERMUTE_EXTENSIONS: CURLOPTTYPE_LONG + 1007,
  /** HTTP/2 initial window update value (long) */
  CURLOPT_HTTP2_WINDOW_UPDATE: CURLOPTTYPE_LONG + 1008,
  /** HTTP/2 streams configuration (string) */
  CURLOPT_HTTP2_STREAMS: CURLOPTTYPE_STRINGPOINT + 1010,
  /** Enable TLS GREASE (long, 0 or 1) */
  CURLOPT_TLS_GREASE: CURLOPTTYPE_LONG + 1011,
  /** TLS extension order (string, dash-separated extension IDs) */
  CURLOPT_TLS_EXTENSION_ORDER: CURLOPTTYPE_STRINGPOINT + 1012,
  /** HTTP/2 stream exclusive flag (long, 0 or 1) */
  CURLOPT_STREAM_EXCLUSIVE: CURLOPTTYPE_LONG + 1013,
  /** Disable TLS key usage check (long, 0 or 1) */
  CURLOPT_TLS_KEY_USAGE_NO_CHECK: CURLOPTTYPE_LONG + 1014,
  /** Enable signed certificate timestamps (long, 0 or 1) */
  CURLOPT_TLS_SIGNED_CERT_TIMESTAMPS: CURLOPTTYPE_LONG + 1015,
  /** Enable OCSP status request (long, 0 or 1) */
  CURLOPT_TLS_STATUS_REQUEST: CURLOPTTYPE_LONG + 1016,
  /** Delegated credentials (string) */
  CURLOPT_TLS_DELEGATED_CREDENTIALS: CURLOPTTYPE_STRINGPOINT + 1017,
  /** TLS record size limit (long) */
  CURLOPT_TLS_RECORD_SIZE_LIMIT: CURLOPTTYPE_LONG + 1018,
  /** TLS key shares limit (long) */
  CURLOPT_TLS_KEY_SHARES_LIMIT: CURLOPTTYPE_LONG + 1019,
  /** Use new ALPS codepoint (long, 0 or 1) */
  CURLOPT_TLS_USE_NEW_ALPS_CODEPOINT: CURLOPTTYPE_LONG + 1020,
  /** Disable HTTP/2 priority frames (long, 0 or 1) */
  CURLOPT_HTTP2_NO_PRIORITY: CURLOPTTYPE_LONG + 1021,
} as const;

export type CurlImpersonateOpt = (typeof CurlImpersonateOpt)[keyof typeof CurlImpersonateOpt];

/**
 * Version info feature bits
 */
export const CurlVersion = {
  CURLVERSION_NOW: 11,
  CURL_VERSION_IPV6: 1 << 0,
  CURL_VERSION_KERBEROS4: 1 << 1,
  CURL_VERSION_SSL: 1 << 2,
  CURL_VERSION_LIBZ: 1 << 3,
  CURL_VERSION_NTLM: 1 << 4,
  CURL_VERSION_GSSNEGOTIATE: 1 << 5,
  CURL_VERSION_DEBUG: 1 << 6,
  CURL_VERSION_ASYNCHDNS: 1 << 7,
  CURL_VERSION_SPNEGO: 1 << 8,
  CURL_VERSION_LARGEFILE: 1 << 9,
  CURL_VERSION_IDN: 1 << 10,
  CURL_VERSION_SSPI: 1 << 11,
  CURL_VERSION_CONV: 1 << 12,
  CURL_VERSION_CURLDEBUG: 1 << 13,
  CURL_VERSION_TLSAUTH_SRP: 1 << 14,
  CURL_VERSION_NTLM_WB: 1 << 15,
  CURL_VERSION_HTTP2: 1 << 16,
  CURL_VERSION_GSSAPI: 1 << 17,
  CURL_VERSION_KERBEROS5: 1 << 18,
  CURL_VERSION_UNIX_SOCKETS: 1 << 19,
  CURL_VERSION_PSL: 1 << 20,
  CURL_VERSION_HTTPS_PROXY: 1 << 21,
  CURL_VERSION_MULTI_SSL: 1 << 22,
  CURL_VERSION_BROTLI: 1 << 23,
  CURL_VERSION_ALTSVC: 1 << 24,
  CURL_VERSION_HTTP3: 1 << 25,
  CURL_VERSION_ZSTD: 1 << 26,
  CURL_VERSION_UNICODE: 1 << 27,
  CURL_VERSION_HSTS: 1 << 28,
  CURL_VERSION_GSASL: 1 << 29,
  CURL_VERSION_THREADSAFE: 1 << 30,
} as const;

export type CurlVersion = (typeof CurlVersion)[keyof typeof CurlVersion];

// Legacy aliases for backwards compatibility
export const CURLcode = CurlCode;
export const CURLoption = CurlOpt;
export const CURLINFO = CurlInfo;
